### PR TITLE
Fix JSR package imports and refactor to use McpServer with optimized async resource loading

### LINKED ISSUE #14: Refactor to use modelcontextprotocol/typescript-sdk high-level API
## Background
As discussed in the recent integration proposal between @yosider/cosense-mcp-server and @takker/cosense-mcp-server, one of the key steps is refactoring the implementation to use the high-level API provided by modelcontextprotocol/typescript-sdk. This will help streamline tool definitions, improve maintainability, and align the server with current best practices. The context for this request is based on the summary from Cosense (Scrapbox) discussions regarding consolidating project features and codebase improvements.

## Tasks
- Refactor the server implementation to leverage the high-level API of modelcontextprotocol/typescript-sdk.
- Consider splitting tool definitions into separate files for maintainability, as discussed in the integration notes.
- Ensure that existing features and supported MCP tools continue to work after the refactor.
- Document any major changes in the README and migration notes to help users transition.
- Collaborate with maintainers and contributors to review and test the new implementation.

## Reference
See the integration plan and reasoning at [@yosider/cosense-mcp-serverと@takker/cosense-mcp-serverを統合](https://scrapbox.io/villagepump/@yosider/cosense-mcp-server%E3%81%A8@takker/cosense-mcp-server%E3%82%92%E7%B5%B1%E5%90%88) for full context and related technical details.

### PR DESCRIPTION
**Pull request by takker99**
Fix #14 
For more information, see https://github.com/takker99/cosense-mcp-server/pull/17

---

This pull request refactors the server architecture to use the new `McpServer` API and modularizes the registration of tools and resources. The previous monolithic `Handlers` class is removed, and individual tools and resources are now registered directly with the server using dedicated functions. This improves maintainability, scalability, and clarity of the codebase.

**Server architecture modernization:**

* Migrated from the legacy `Server` and `Handlers` class to the new `McpServer` API, removing the `Handlers` class and its associated resource and tool management logic from `src/handlers.ts`. Tool and resource registration is now handled via dedicated registration functions. [[1]](diffhunk://#diff-c77b89ae7ba2627f28f4b8fe20ecbb5c169809193c3a3cfd404cd93f12750b83L1-L95) [[2]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L3-R24)

**Tool registration refactor:**

* Replaced individual tool exports and the generic tool interface with modular registration functions (`registerGetPageTool`, `registerInsertLinesTool`, `registerListPagesTool`, `registerSearchPagesTool`) that directly register each tool with the server using the new API. [[1]](diffhunk://#diff-c21e69fdbee88b44a5068c01183f235397a8573eab85bba90f757dada4ab30afL2-R28) [[2]](diffhunk://#diff-96150c90428667f666bf4b3c6d59d35e717188277f7c5167b867382d7fa4491bL2-R31) [[3]](diffhunk://#diff-e76617e97f674dad7c984e4970ea262f6bc54fc78349ee6d345cd29faa04ec20L2-R25) [[4]](diffhunk://#diff-bb02a16f48d1819b0f74609c1354f0ff2a7033d040424d7c30767ab9ae44ee2dL3-R32) [[5]](diffhunk://#diff-a7cc19a6bb39b048b05c5dd7812537802e591624e72321e0ce4778b18d4bf7e1L1-L5)

**Resource registration refactor:**

* Added `registerPageResources` in `src/resources/pageResources.ts` to asynchronously register each Cosense page as a resource with the server, replacing the previous resource management logic. [[1]](diffhunk://#diff-117ba395409e93551ee6cee91f30cbb8ef849a2b0268b7091dd9b7cccf0d6f44R1-R65) [[2]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L37-R55)

**Configuration and error handling updates:**

* Updated error handling in `getConfig` to use single quotes for consistency and improved error reporting in the server startup logic. [[1]](diffhunk://#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012L11-R11) [[2]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L37-R55)

**Minor improvements:**

* Fixed a minor formatting issue in the logger utility to ensure consistent code style.

### CODE REVIEW

File: src/tools/insertLinesTool.ts [hunk 1]
```diff
@@ -1,72 +1,62 @@
...
+          content: [
+            {
+              type: 'text',
+              text: `Successfully inserted lines.`,
+            },
+          ],
+        };
+      } else {
+        throw unwrapErr(result);
+      }
```
Comment (takker99) [inline src/tools/insertLinesTool.ts:59]: Fixed! Changed to return content with `isError: true` instead of throwing the error, consistent with other tools like `getPageTool`.

File: src/resources/pageResources.ts
Comment (takker99) [inline src/resources/pageResources.ts:1]: Done! Deleted the unused `src/resource.ts` file.

File: src/handlers.ts
Comment (takker99) [inline src/handlers.ts:1]: Done! Deleted the unused `src/tools/types.ts` file as well.

File: src/tools/getPageTool.ts [hunk 2]
```diff
@@ -1,53 +1,46 @@
 import { getPage } from '@cosense/std/rest';
-import type { CallToolResult } from '@modelcontextprotocol/sdk/types.js';
+import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
 import { isErr, unwrapErr, unwrapOk } from 'option-t/plain_result';
+import { z } from 'zod';
```
Comment (takker99) [inline src/tools/getPageTool.ts:4]: Good catch! Added `zod` to the dependencies in `package.json` since we're using it directly in the tools.

**Review by takker99 — COMMENTED** [review]
(deleted)

File: src/tools/insertLinesTool.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (takker99) [reply src/tools/insertLinesTool.ts:59]: Fixed! Changed to return content with `isError: true` instead of throwing the error, consistent with other tools like `getPageTool`.

File: src/tools/getPageTool.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (takker99) [reply src/tools/getPageTool.ts:4]: Good catch! Added `zod` to the dependencies in `package.json` since we're using it directly in the tools.

File: src/handlers.ts
[the remark this answers is not in the document]
Comment (takker99) [reply src/handlers.ts:1]: Done! Deleted the unused `src/tools/types.ts` file as well.

**Comment by yosider** [comment]
Thanks for the changes!
